database_type: postgres
database_table: pyway_migrations
database_host: localhost
database_port: 5432
database_name: <your_database_name>
database_username: <your_database_username>
database_password: <your_database_password>
database_migration_dir: DB\Schemas\migration
